
package com.mxg.bybo.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-22T18:00:18.190+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class SmsPortSoap_SmsPortSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://support.microsoft.com/", "SmsPort");

    private SmsPortSoap_SmsPortSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SmsPort.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmsPort ss = new SmsPort(wsdlURL, SERVICE_NAME);
        SmsPortSoap port = ss.getSmsPortSoap();  
        {
        System.out.println("Invoking sendSms...");
        java.lang.String _sendSms_epid = "70505";
        java.lang.String _sendSms_userName = "jtgw";
        java.lang.String _sendSms_password = "185c0055f0d25b8f";
        java.lang.String _sendSms_phone = "18512560705";
        java.lang.String _sendSms_content = "您的验证码是：123456，此验证码只用于您登录拜博口腔官网或找回密码，请勿提供给他人。【拜博医疗集团】";
        java.lang.String _sendSms__return = port.sendSms(_sendSms_epid, _sendSms_userName, _sendSms_password, _sendSms_phone, _sendSms_content);
        System.out.println("sendSms.result=" + _sendSms__return);


        }

        System.exit(0);
    }

}
