
package com.mxg.bybo.sms;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-22T18:00:18.247+08:00
 * Generated source version: 3.1.10
 * 
 */
public final class SmsPortSoap_SmsPortSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://support.microsoft.com/", "SmsPort");

    private SmsPortSoap_SmsPortSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SmsPort.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmsPort ss = new SmsPort(wsdlURL, SERVICE_NAME);
        SmsPortSoap port = ss.getSmsPortSoap12();  
        
        {
        System.out.println("Invoking sendSmsEx...");
        java.lang.String _sendSmsEx_epid = "";
        java.lang.String _sendSmsEx_userName = "";
        java.lang.String _sendSmsEx_password = "";
        java.lang.String _sendSmsEx_phone = "";
        java.lang.String _sendSmsEx_content = "";
        java.lang.String _sendSmsEx_spnum = "";
        java.lang.String _sendSmsEx_msgid = "";
        java.lang.String _sendSmsEx__return = port.sendSmsEx(_sendSmsEx_epid, _sendSmsEx_userName, _sendSmsEx_password, _sendSmsEx_phone, _sendSmsEx_content, _sendSmsEx_spnum, _sendSmsEx_msgid);
        System.out.println("sendSmsEx.result=" + _sendSmsEx__return);


        }
        {
        System.out.println("Invoking userMo...");
        java.lang.String _userMo_epid = "";
        java.lang.String _userMo_userName = "";
        java.lang.String _userMo_password = "";
        java.lang.String _userMo__return = port.userMo(_userMo_epid, _userMo_userName, _userMo_password);
        System.out.println("userMo.result=" + _userMo__return);


        }
        {
        System.out.println("Invoking sendSmsAT...");
        java.lang.String _sendSmsAT_epid = "";
        java.lang.String _sendSmsAT_userName = "";
        java.lang.String _sendSmsAT_password = "";
        java.lang.String _sendSmsAT_phone = "";
        java.lang.String _sendSmsAT_content = "";
        java.lang.String _sendSmsAT_spnum = "";
        java.lang.String _sendSmsAT_msgid = "";
        java.lang.String _sendSmsAT_sendtime = "";
        java.lang.String _sendSmsAT__return = port.sendSmsAT(_sendSmsAT_epid, _sendSmsAT_userName, _sendSmsAT_password, _sendSmsAT_phone, _sendSmsAT_content, _sendSmsAT_spnum, _sendSmsAT_msgid, _sendSmsAT_sendtime);
        System.out.println("sendSmsAT.result=" + _sendSmsAT__return);


        }
        {
        System.out.println("Invoking userOverage...");
        java.lang.String _userOverage_epid = "";
        java.lang.String _userOverage_userName = "";
        java.lang.String _userOverage_password = "";
        java.lang.String _userOverage__return = port.userOverage(_userOverage_epid, _userOverage_userName, _userOverage_password);
        System.out.println("userOverage.result=" + _userOverage__return);


        }
        {
        System.out.println("Invoking send...");
        java.lang.String _send_epid = "";
        java.lang.String _send_userName = "";
        java.lang.String _send_password = "";
        java.lang.String _send_content = "";
        java.lang.String _send__return = port.send(_send_epid, _send_userName, _send_password, _send_content);
        System.out.println("send.result=" + _send__return);


        }
        {
        System.out.println("Invoking sendAT...");
        java.lang.String _sendAT_epid = "";
        java.lang.String _sendAT_userName = "";
        java.lang.String _sendAT_password = "";
        java.lang.String _sendAT_content = "";
        java.lang.String _sendAT__return = port.sendAT(_sendAT_epid, _sendAT_userName, _sendAT_password, _sendAT_content);
        System.out.println("sendAT.result=" + _sendAT__return);


        }
        {
        System.out.println("Invoking chkBadPhone...");
        java.lang.String _chkBadPhone_phone = "";
        java.lang.String _chkBadPhone__return = port.chkBadPhone(_chkBadPhone_phone);
        System.out.println("chkBadPhone.result=" + _chkBadPhone__return);


        }
        {
        System.out.println("Invoking changePass...");
        java.lang.String _changePass_epid = "";
        java.lang.String _changePass_userName = "";
        java.lang.String _changePass_oldPass = "";
        java.lang.String _changePass_newPass = "";
        java.lang.String _changePass_confirmPassword = "";
        java.lang.String _changePass__return = port.changePass(_changePass_epid, _changePass_userName, _changePass_oldPass, _changePass_newPass, _changePass_confirmPassword);
        System.out.println("changePass.result=" + _changePass__return);


        }
        {
        System.out.println("Invoking sendSms...");
        java.lang.String _sendSms_epid = "";
        java.lang.String _sendSms_userName = "";
        java.lang.String _sendSms_password = "";
        java.lang.String _sendSms_phone = "";
        java.lang.String _sendSms_content = "";
        java.lang.String _sendSms__return = port.sendSms(_sendSms_epid, _sendSms_userName, _sendSms_password, _sendSms_phone, _sendSms_content);
        System.out.println("sendSms.result=" + _sendSms__return);


        }
        {
        System.out.println("Invoking chkBadWord...");
        java.lang.String _chkBadWord_content = "";
        java.lang.String _chkBadWord__return = port.chkBadWord(_chkBadWord_content);
        System.out.println("chkBadWord.result=" + _chkBadWord__return);


        }

        System.exit(0);
    }

}
