package com.mxg.bybo.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-22T18:00:18.323+08:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://support.microsoft.com/", name = "SmsPortHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SmsPortHttpPost {

    /**
     * <br><br><b>说明：</b><br>短信发送方法，最多一次可发送1000个号码。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限1000个）、内容等为空或内容长度超过210<br>02：密码错误<br>10：余额不足<br>-99：服务器接受失败<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "SendSmsEx")
    public java.lang.String sendSmsEx(
        @WebParam(partName = "Epid", name = "Epid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password,
        @WebParam(partName = "phone", name = "phone", targetNamespace = "http://support.microsoft.com/")
        java.lang.String phone,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content,
        @WebParam(partName = "spnum", name = "spnum", targetNamespace = "http://support.microsoft.com/")
        java.lang.String spnum,
        @WebParam(partName = "msgid", name = "msgid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String msgid
    );

    /**
     * <br><br><b>获取用户上行：</b><br>需要输入ID\账户\密码进行验证。<br><b>返回状态：</b><br><br>01：用户鉴权失败<br>02：用户信息不能为空<br>00：标记已读成功<br>03：标记已读失败,可能传递ID非法<br>04：暂无上行数据<br>正常返回：消息id|手机号码|上行内容|上行时间<br>99：服务器接受失败<br>
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "User_Mo")
    public java.lang.String userMo(
        @WebParam(partName = "EPID", name = "EPID", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password
    );

    /**
     * 返回值说明:<br>00:成功<br>01:号码或内容为空、号码超过上限<br>02:登陆失败<br>10:余额不足<br>-99:服务器接收失败<br>注:<br>返回其他字符,比如返回短信中某一字词时,表示该短信内容存在敏感字符
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "SendSmsAT")
    public java.lang.String sendSmsAT(
        @WebParam(partName = "Epid", name = "Epid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password,
        @WebParam(partName = "phone", name = "phone", targetNamespace = "http://support.microsoft.com/")
        java.lang.String phone,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content,
        @WebParam(partName = "spnum", name = "spnum", targetNamespace = "http://support.microsoft.com/")
        java.lang.String spnum,
        @WebParam(partName = "msgid", name = "msgid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String msgid,
        @WebParam(partName = "sendtime", name = "sendtime", targetNamespace = "http://support.microsoft.com/")
        java.lang.String sendtime
    );

    /**
     * <br><br><b>获取用户条数：</b><br>需要输入ID\账户\密码进行验证。<br><b>返回状态：</b><br><br>01：用户鉴权失败<br>02：用户信息不能为空<br>99：服务器接受失败<br>
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "User_Overage")
    public java.lang.String userOverage(
        @WebParam(partName = "EPID", name = "EPID", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "Password", name = "Password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password
    );

    /**
     * <br><br><b>说明：</b><br>短信发送方法。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限）、内容等为空或内容长度超过300<br>02：密码错误<br>10：余额不足<br>-99：服务器接受失败<br>content参数值格式：&lt;SmsList&gt;&lt;row phone="手机号码" info="发送内容" spnumber="拓展号码" msgid="消息ID" /&gt;&lt;/SmsList&gt;<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字<br>
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "Send")
    public java.lang.String send(
        @WebParam(partName = "Epid", name = "Epid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content
    );

    /**
     * 返回值说明:<br>00:成功<br>01:号码或内容为空<br>02:登陆失败<br>03:短信内容长度超限<br>10:余额不足<br>-99:服务器接收失败<br>注:<br>返回其他字符,比如返回短信中某一字词时,表示该短信内容存在敏感字符
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "SendAT")
    public java.lang.String sendAT(
        @WebParam(partName = "Epid", name = "Epid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content
    );

    /**
     * <br><br><b>检查黑名单：</b><br>如果有黑名单将返回黑名单，否则返回为空。
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "ChkBadPhone")
    public java.lang.String chkBadPhone(
        @WebParam(partName = "phone", name = "phone", targetNamespace = "http://support.microsoft.com/")
        java.lang.String phone
    );

    /**
     * <br><br><b>更改密码：</b><br>需要输入旧密码进行验证。<br><br><b>返回状态：</b><br><br>00：成功<br>01：用户鉴权失败(可能登录信息不正确或超过安全限制，每分钟仅能更改一次，共有5次更改机会，超过五次请联系我们处理。)<br>02：两次输入密码不匹配<br>99：服务器接受失败<br>
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "ChangePass")
    public java.lang.String changePass(
        @WebParam(partName = "EPID", name = "EPID", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "OldPass", name = "OldPass", targetNamespace = "http://support.microsoft.com/")
        java.lang.String oldPass,
        @WebParam(partName = "NewPass", name = "NewPass", targetNamespace = "http://support.microsoft.com/")
        java.lang.String newPass,
        @WebParam(partName = "Confirm_Password", name = "Confirm_Password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String confirmPassword
    );

    /**
     * <br><br><b>说明：</b><br>短信发送方法，最多一次可发送50个号码。<br><br><br><b>状态报告说明：</b><br>00：成功<br>01：号码（超过上限1000个）、内容等为空或内容长度超过210<br>02：密码错误<br>10：余额不足<br>-99：服务器接受失败<br>当返回值非以上定义，表现为某个字、词组时表示内容有屏蔽字。
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "SendSms")
    public java.lang.String sendSms(
        @WebParam(partName = "Epid", name = "Epid", targetNamespace = "http://support.microsoft.com/")
        java.lang.String epid,
        @WebParam(partName = "User_Name", name = "User_Name", targetNamespace = "http://support.microsoft.com/")
        java.lang.String userName,
        @WebParam(partName = "password", name = "password", targetNamespace = "http://support.microsoft.com/")
        java.lang.String password,
        @WebParam(partName = "phone", name = "phone", targetNamespace = "http://support.microsoft.com/")
        java.lang.String phone,
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content
    );

    /**
     * <br><br><b>检查屏蔽字：</b><br>如果有屏蔽字将返回屏蔽字，否则返回为空。
     */
    @WebResult(name = "string", targetNamespace = "http://support.microsoft.com/", partName = "Body")
    @WebMethod(operationName = "ChkBadWord")
    public java.lang.String chkBadWord(
        @WebParam(partName = "content", name = "content", targetNamespace = "http://support.microsoft.com/")
        java.lang.String content
    );
}
